mz07 :
# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
# Position Controllers ---------------------------------------
  j_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 100, i: 10, d: 0, i_clamp: 100}
  j_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 1000, i: 500, d: 0, i_clamp: 500}
  j_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J3
    pid: {p: 100, i: 10, d: 0, i_clamp: 100}
  j_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: J4
    pid: {p: 100, i: 10, d: 0, i_clamp: 100}
  j_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: J5
    pid: {p: 10, i: 1, d: 0, i_clamp: 100}
  j_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: J6
    pid: {p: 10, i: 1, d: 0, i_clamp: 100}