# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  J1:
    has_velocity_limits: true
    max_velocity: 7.85398185
    has_acceleration_limits: false
    max_acceleration: 0
  J2:
    has_velocity_limits: true
    max_velocity: 6.63225134
    has_acceleration_limits: false
    max_acceleration: 0
  J3:
    has_velocity_limits: true
    max_velocity: 9.075712360000001
    has_acceleration_limits: false
    max_acceleration: 0
  J4:
    has_velocity_limits: true
    max_velocity: 9.59931115
    has_acceleration_limits: false
    max_acceleration: 0
  J5:
    has_velocity_limits: true
    max_velocity: 9.59931115
    has_acceleration_limits: false
    max_acceleration: 0
  J6:
    has_velocity_limits: true
    max_velocity: 17.453293
    has_acceleration_limits: false
    max_acceleration: 0